"""
Base Strategy Class
Foundation for all trading strategies
"""
from __future__ import annotations

import uuid
from abc import ABC, abstractmethod
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from pydantic import BaseModel

from app.backend.agents.specialized_agents import (
    QuantAgent,
    RiskAgent,
    ExecutionAgent,
    ForecastAgent,
)
from app.backend.agents.base_agent import AgentDecision
from app.backend.database import execute_sql
from app.backend.config import get_settings


class StrategyParameters(BaseModel):
    """Strategy configuration parameters"""

    region_id: str = 'NSW1'
    position_size_mw: float = 100.0
    max_position_mw: float = 500.0
    stop_loss_pct: float = 5.0
    take_profit_pct: float = 10.0
    risk_per_trade_pct: float = 2.0
    use_forecast: bool = True
    forecast_confidence_threshold: float = 0.5


class StrategySignal(BaseModel):
    """Trading signal generated by strategy"""

    signal_type: str  # 'ENTRY', 'EXIT', 'REBALANCE'
    action: str  # 'BUY', 'SELL', 'HOLD', 'CLOSE'
    instrument: str
    volume_mw: float
    target_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    confidence: float
    reasoning: str
    metadata: Dict[str, Any] = {}


class Position(BaseModel):
    """Open trading position"""

    position_id: str
    instrument: str
    entry_price: float
    volume_mw: float
    entry_timestamp: datetime
    stop_loss: float
    take_profit: float
    unrealized_pnl: float = 0.0


class BaseStrategy(ABC):
    """
    Base class for all trading strategies
    Provides agent integration, position management, and signal generation
    """

    def __init__(
        self,
        strategy_id: str,
        strategy_name: str,
        strategy_type: str,
        description: str,
        parameters: StrategyParameters,
    ):
        """
        Initialize base strategy

        Args:
            strategy_id: Unique strategy identifier
            strategy_name: Human-readable name
            strategy_type: Strategy type
            description: Strategy description
            parameters: Strategy parameters
        """
        self.strategy_id = strategy_id
        self.strategy_name = strategy_name
        self.strategy_type = strategy_type
        self.description = description
        self.parameters = parameters
        self.catalog = get_settings().apex_catalog

        # Initialize agents
        self.quant_agent = QuantAgent(agent_id=f'{strategy_id}-quant')
        self.risk_agent = RiskAgent(agent_id=f'{strategy_id}-risk')
        self.execution_agent = ExecutionAgent(agent_id=f'{strategy_id}-exec')
        self.forecast_agent = ForecastAgent(agent_id=f'{strategy_id}-forecast')

        # Current positions
        self.positions: List[Position] = []

    @abstractmethod
    async def generate_signal(self) -> StrategySignal:
        """
        Generate trading signal based on strategy logic
        Must be implemented by each strategy

        Returns:
            Trading signal
        """
        pass

    async def execute_strategy(self) -> StrategySignal:
        """
        Full strategy execution pipeline with agent collaboration

        Returns:
            Final trading signal
        """
        # Step 1: Strategy generates signal
        signal = await self.generate_signal()

        # Step 2: Risk agent validates
        risk_check = await self._check_risk(signal)
        if not risk_check['approved']:
            # Risk agent vetoed - modify or reject signal
            signal.action = 'HOLD'
            signal.reasoning = f"Risk veto: {risk_check['reason']}"
            signal.confidence = 0.0
            return signal

        # Step 3: Execution agent optimizes
        optimized_signal = await self._optimize_execution(signal)

        # Step 4: Log signal
        await self._log_signal(optimized_signal)

        return optimized_signal

    async def _check_risk(self, signal: StrategySignal) -> Dict[str, Any]:
        """
        Risk agent validates signal

        Args:
            signal: Proposed signal

        Returns:
            Risk check result
        """
        # Get current portfolio exposure
        total_position = sum(p.volume_mw for p in self.positions)

        # Check position size limit
        if signal.action in ['BUY', 'SELL']:
            new_position = total_position + signal.volume_mw
            if new_position > self.parameters.max_position_mw:
                return {
                    'approved': False,
                    'reason': f'Position limit exceeded: {new_position} MW > {self.parameters.max_position_mw} MW',
                }

        # Risk agent makes final decision
        risk_instruction = f"""
        Evaluate this trading signal for risk:
        - Action: {signal.action}
        - Instrument: {signal.instrument}
        - Volume: {signal.volume_mw} MW
        - Current total position: {total_position} MW
        - Max position limit: {self.parameters.max_position_mw} MW
        - Confidence: {signal.confidence}

        Approve or veto this trade.
        """

        try:
            risk_decision = await self.risk_agent.act(risk_instruction)
            approved = risk_decision.decision_type == 'APPROVE'

            return {
                'approved': approved,
                'reason': risk_decision.reasoning,
                'adjusted_volume': risk_decision.volume_mw,
            }
        except Exception as e:
            # If risk agent fails, be conservative
            return {'approved': False, 'reason': f'Risk agent error: {str(e)}'}

    async def _optimize_execution(self, signal: StrategySignal) -> StrategySignal:
        """
        Execution agent optimizes signal

        Args:
            signal: Validated signal

        Returns:
            Optimized signal
        """
        exec_instruction = f"""
        Optimize execution for this trade:
        - Action: {signal.action}
        - Instrument: {signal.instrument}
        - Volume: {signal.volume_mw} MW
        - Target price: {signal.target_price}

        Determine optimal execution strategy and timing.
        """

        try:
            exec_decision = await self.execution_agent.act(exec_instruction)

            # Update signal with execution details
            if 'execution_strategy' in exec_decision.metadata:
                signal.metadata['execution_strategy'] = exec_decision.metadata[
                    'execution_strategy'
                ]
            if exec_decision.price:
                signal.target_price = exec_decision.price

            return signal
        except Exception:
            # If execution agent fails, return original signal
            return signal

    async def _log_signal(self, signal: StrategySignal):
        """Log signal to database"""
        try:
            sql = f"""
            INSERT INTO {self.catalog}.strategy.live_signals
            (signal_id, strategy_id, timestamp, signal_type, instrument, action, volume_mw, price, confidence, reasoning, executed)
            VALUES (
                '{str(uuid.uuid4())}',
                '{self.strategy_id}',
                current_timestamp(),
                '{signal.signal_type}',
                '{signal.instrument}',
                '{signal.action}',
                {signal.volume_mw},
                {signal.target_price if signal.target_price else 'NULL'},
                {signal.confidence},
                '{signal.reasoning.replace("'", "''")}',
                false
            )
            """
            await execute_sql(sql)
        except Exception as e:
            print(f"Failed to log signal: {e}")

    async def update_positions(self, current_prices: Dict[str, float]):
        """
        Update position valuations

        Args:
            current_prices: Current market prices
        """
        for position in self.positions:
            current_price = current_prices.get(position.instrument, position.entry_price)
            position.unrealized_pnl = (
                current_price - position.entry_price
            ) * position.volume_mw

    def get_positions(self) -> List[Position]:
        """Get current positions"""
        return self.positions

    def get_total_exposure(self) -> float:
        """Get total position exposure in MW"""
        return sum(abs(p.volume_mw) for p in self.positions)

    async def save_to_database(self):
        """Save strategy configuration to database"""
        try:
            sql = f"""
            INSERT INTO {self.catalog}.strategy.strategies
            (strategy_id, strategy_name, strategy_type, description, agent_id, region_id, parameters, status, created_at, created_by)
            VALUES (
                '{self.strategy_id}',
                '{self.strategy_name}',
                '{self.strategy_type}',
                '{self.description}',
                '{self.quant_agent.agent_id}',
                '{self.parameters.region_id}',
                '{self.parameters.model_dump_json()}',
                'BACKTEST',
                current_timestamp(),
                'system'
            )
            """
            await execute_sql(sql)
        except Exception as e:
            print(f"Failed to save strategy: {e}")
